uploads = []
outputs = []

[[generated]]
id = "Ef3XjAPek0vZWd7S9cww7"
uri = "file://artifacts/matchpit/public/venues/venue1.png"
type = "image"
title = "top-down football turf"

[[generated]]
id = "QuJF3Oso69jNA6m524tAL"
uri = "file://artifacts/matchpit/public/venues/venue2.png"
type = "image"
title = "cricket pitch wide angle"

[[generated]]
id = "lL8anSh4FSSinoFi-bHpB"
uri = "file://artifacts/matchpit/public/venues/venue3.png"
type = "image"
title = "badminton court indoor"

[[generated]]
id = "NMteJPKUb-43DEgObPeIh"
uri = "file://artifacts/matchpit/public/venues/venue4.png"
type = "image"
title = "tennis court wide angle"
