/**
 * Deployment Version / Worker Compatibility Guard
 * 
 * Tracks the current deployment version to prevent old workers from picking up
 * incompatible payloads from new deployments, or vice versa.
 */

// In production, this should ideally be populated during the CI build process
// For example, reading from a file generated by Webpack/Vite or passed as an ENV var.
export const DEPLOYMENT_VERSION = process.env.DEPLOYMENT_VERSION || "v1.0.0";

/**
 * Validates if the job payload's version is compatible with this worker's version.
 * Basic implementation: must match exactly.
 * Advanced implementation: semantic versioning matching (e.g., ^1.0.0)
 */
export function isJobCompatible(jobVersion?: string): boolean {
  if (!jobVersion) return true; // Legacy jobs without version
  
  // For safety, require exact match or backward-compatible minor versions.
  // We'll enforce exact match for simplicity in Phase 14 unless specified.
  return jobVersion === DEPLOYMENT_VERSION;
}
